config/routes.rb
Rails.application.routes.draw do
  get 'password/reset', to:'password_resets#new', as: :reset_password
  post 'password/reset', to:'password_resets#create'
  
  get 'password/reset/edit', to:'password_resets#edit', as: :edit_reset_password
  patch 'password/reset/edit', to:'password_resets#update'
  
  get 'password', to: 'passwords#edit', as: :edit_password
  patch 'password', to: 'passwords#update'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # get '/resgister', to: 'registration#index', as: :user_registration
  # get '/resgister/create', to: 'registration#create', as: :user_registration_create
  resources :users, as: :users

  root to: 'home#index' 

  get '/about-us', to: 'about#index' , as: :about # prefix
  # URI Pattern   , Controller_name#function(action)

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end
 

app/models/Current.rb
# Model "Current" created for making user attribute knows globally
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    
    validates :email, 
                presence: true, 
                uniqueness: true,
                format: {
                    with: URI::MailTo::EMAIL_REGEXP, 
                    message: "must be a valid email address"
                }
                
    validates :name, 
            presence: true,
            length: { 
                maximum: 50, 
                too_long: "%{count} characters is the maximum allowed"
            } 

    validates :password, 
            confirmation: true, 
            length: { 
                minimum: 3 
            }, 
            allow_blank: false

    # validates :password_confirmation, 
    #         length: { 
    #             minimum: 3 
    #         }, 
    #         allow_blank: false
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  # GET /about
  def index
    @about_value = "About us"
    # @current_page = 'about'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    before_action :set_current_user # This function is called from SessionsHelper
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
    @faq_value = "This is the index page for FaqController Test"
    @user = User.find_by(email: params[:email]) # this is the user that will be logged in"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  # GET to home page
  def index
    @control_value = "Welcome to the Home Controller and show it on home page html.erb"
    # @current_page = 'home'
    if session[:user_id]
      @user = User.find_by_id(session[:user_id])
      # flash.now[:notice] = "Logged in successfully"
      # flash.now[:alert] = "Invalid username or password"
    end
    
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  # GET /password_reset
  def new
  end
  # POST /password_reset
  def create
    user_reset = User.find_by(email: params[:email])

    if user_reset.present?
        # Send email
        # "reset" function created on the mailers/password_mailer.rb
        PasswordMailer.with(user: user_reset).reset.deliver_now

        redirect_to root_path, notice: "Email of the user #{user_reset.email}, we have sent a link to your inbox to reset your password"
    else
        flash.now[:alert] = "Email does not exist"
        render :new
    end
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    # With keyword "rescue" catch an exception of expired token
    rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to login_path, alert: "Your token has expired, please try again later"
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)

      redirect_to login_path, notice: "Your password has been updated successfully"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in! # This function is called from SessionsHelper

  def edit

  end

  def update
    if Current.user.update(password_params)
        redirect_to root_path, notice: "Password updated successfully"
    else
        render :edit
    end
  end

  private

  def password_params
      params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /login
  def new

    if Current.user # Check if current user is already logged in
        redirect_to root_path
    end
  end

  # POST /login
  def create
    user = User.find_by(email: params[:email])
    if user.present? and user.authenticate(params[:password])
        # log_in_user is a function that exists in helpers/sessions_helper.rb which is included in the application_controller.rb (Global function)
        log_in_user(user)
        # session[:user_id] = current_user.id
        redirect_to root_path, notice: "You logged in"
    else
      flash.now[:alert] = "Login or password is Invalid"
      render :new
    end
  end

  # DELETE /logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out !!!"
  end

  # private
  #   # Only allow a list of trusted parameters through.
  #   def user_params
  #     params.require(:user).permit(:email, :password)
  #   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    # render plain: user_params
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :passowrd_confirmation)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user.
    def log_in_user(user)
        session[:user_id] = user.id
        Current.user = user
    end

    # Returns the current logged-in user (if any).
    def set_current_user
        Current.user ||= User.find_by(id: session[:user_id])
    end

    def require_user_logged_in!
        redirect_to login_path, alert: "You must be logged in to do that." if Current.user.nil?
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1><%=  @about_value %></h1>
</div>

app/views/faq/index.html.erb
<h1>This is FAQ index page</h1>
<p>Find me in app/views/faq/index.html.erb</p>

app/views/flashs/_message.html.erb
<%# flash.now[:status_name] is a Rails object array that has all messages from a controller that appears once on the page %>
<% if flash.now[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash.now[:notice] %>
    </div>
<% end %>

<% if flash.now[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash.now[:alert] %>
    </div>
<% end %>

app/views/home/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1><%=  @control_value %></h1>

</div>

<% if Current.user %>
    <h1 class="alert alert-success"><%=  Current.user.name %></h1>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to  "NGA Ruby on Rails", root_path, class: "navbar-brand" %>
    
    <%# <a class="navbar-brand" href="/">NGA Ruby on Rails</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">

        <%# <li class="nav-item">
           link_to_unless_current("Home", {controller: "home", action: "index" }) 
        </li> %>
        <li class="nav-item">

          <%# Check if current page is active %>
          <% is_active = "active" if controller.controller_name == "home" %>    
          <%# link_to is a Rails framework Syntax  %>
          <%= link_to  "Home", root_path, class: "nav-link #{is_active}", aria: {current: "page"} %>
          <%# link_to  "Home", root_path, class: "nav-link", "aria-current" => "page" %>
        </li>
        <li class="nav-item">

          <% is_active = controller.controller_name == "about" ? "active" : "" %> 

          <%= link_to  "About", about_path, class: "nav-link #{is_active}" %>
        </li>

        <li class="nav-item">

          <% is_active = controller.controller_name == "users" && controller.action_name == "index" ? "active" : "" %> 

          <%= link_to  "All Users", users_path, class: "nav-link #{is_active}" %>
        </li>

        <% is_active = controller.controller_name == "users" || controller.controller_name == "sessions" ? "active" : "" %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle <%= is_active %>" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if Current.user %>
                <%= Current.user.name %>
              <% else %>
              Account
            <% end %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if Current.user %>
                  <li> <%= link_to 'Profile', user_path(Current.user), class: "dropdown-item" %></li>
                  <li> <%= link_to 'Edit Password', edit_password_path, class: "dropdown-item" %></li>
                  <li><%= button_to  "Logout", logout_path, method: :delete, class: "dropdown-item"%></li>
                  
              <% else %>
                  <li><%= link_to  "Login", login_path, class: "dropdown-item"%></li>
                  <li><%= link_to  "Register", new_user_path, class: "dropdown-item"%></li>
                  
              <% end %>
          </ul>
        </li>
      </ul> 
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NgaRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  
  <body>
    <%# Partial is a Rails syntax that includes html.erb %>
    <%= render partial: "layouts/navbar" %>
    <div class="container">
        <%= render partial: "flashs/message" %>

        <h2>Controller name : <%= controller.controller_name %></h2>

        <%= yield %>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/password_resets/_form.html.erb
<%= form_with(url: reset_password_path) do |form| %>
    <% if flash[:alert] %>
    <div class="alert alert-danger mt-4" role="alert">
      <ul>
          <li><%= flash[:alert] %></li>
      </ul>
    </div>
  <% end %>
    <h1><%= flash[:alert] %></h1>
  <div class="mb-3">
    <%= form.label :email, class:"form-label" %>
    <%= form.text_field :email, class: "form-control", required: true, placeholder: "Enter your Email" %>
  </div>
  <div class="mb-3">
     <%= form.submit value:"Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/password_resets/_form_edit.html.erb
<%= form_with(model: @user, url: edit_reset_password_path(token: params[:token])) do |form| %>
    <% if form.object.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% form.object.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :password, class:"form-label" %>
      <%= form.password_field :password, required: true, class: "form-control", placeholder: "Enter new Password"  %>
    </div>

    <div class="mb-3">
      <%= form.label :password_confirmation, class:"form-label" %>
      <%= form.password_field :password_confirmation, required: true, class: "form-control", placeholder: "Confirmation Password"  %>
    </div>

    <div class="mb-3">
      <%= form.submit value:"Update Password", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_resets/edit.html.erb
<h1>Edit Password for <%= @user.name  %> </h1>

<%= render partial: 'form_edit' %>

app/views/password_resets/new.html.erb
<h1>Password Reset</h1>

<%# Partial is a Rails syntax that includes _from.html.erb %>
<%= render partial: 'form' %>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name, required: true, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class:"form-label" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :password, class:"form-label" %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation, class:"form-label" %>
    <%= form.password_field :password_confirmation, class: "form-control"  %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password digest:</strong>
    <%= user.password_digest %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%# Partial is a Rails syntax that includes _from.html.erb %>
<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
<%# each loop is a Rails syntax that includes _from.html.erb %>

  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render partial: "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<h1> Profile </h1>
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>